version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"
