version: "3.8"
services:
  frontend-static:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - IMAGE_NAME=frontend-static
        - FRONTEND_VERSION=0.0.1
        - SERVER_NAME=localhost
        - PORT=80
    image: ghcr.io/codeforphilly/balancer-main/frontend:0.0.1-static
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=https://devnull-as-a-service.com/dev/null
