version: '3.8'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    image: docker.fakecodeforphillydomain.com/balancer_backend/local
    command: ["/app/tools/wait-for-it.sh", "db:5432", "--", "python", "/app/backend/manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=balancer.settings
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./:/usr/src/app/frontend:delegated"
      - "/usr/src/app/frontend/node_modules/"
    depends_on:
      - backend
