version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=balancer
      - POSTGRES_PASSWORD=balancer
      - POSTGRES_DB=balancer_dev
    ports:
    - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2  
  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: balancer-noreply@codeforphilly.org
  #     PGADMIN_DEFAULT_PASSWORD: balancer
  #     # PGADMIN_LISTEN_PORT = 80
  #   # volumes:
  #   #   - ./pgadmin-data:/var/lib/pgadmin
  #   #       # PGADMIN_LISTEN_PORT = 80
  #   ports:
  #     - "5050:80"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.168.0.4
  backend:
    image: balancer-backend
    build: ./server
<<<<<<< HEAD:docker-compose.dev.yml
<<<<<<< HEAD:docker-compose.dev.yml
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
=======
>>>>>>> ed1b2e3bc80a77cb1283844d0c153fa1f79d9d76:docker-compose.yml
=======
    command: python manage.py runserver 0.0.0.0:8000
>>>>>>> 5d9968afe8f5ab373ab0379485cea79ba3253193:docker-compose.yml
    ports:
      - "8000:8000"
    env_file:
      - ./config/env/env.dev
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/server
    networks:
      app_net:
        ipv4_address: 192.168.0.3
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
      args:
        - IMAGE_NAME=balancer-frontend
        - FRONTEND_VERSION=0.0.1
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
        # - VITE_API_BASE_URL=https://balancertestsite.com/
    volumes:
        - "./frontend:/usr/src/app:delegated"
        - "/usr/src/app/node_modules/"
    depends_on:
      - backend
    networks:
      app_net:
        ipv4_address: 192.168.0.5
volumes:
  postgres_data:
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1