version: "3.8"
services:
  react-app:
    image: test4
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./app:/app/delegated"
      - "/app/node_modules/"
