version: "3.8"
services:
  react-app:
    image: test5
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"
