version: "3"
services:
  backend:
    image: docker.fakecodeforphillydomain.com/balancer_backend/local:latest
    container_name: balancer-backend
    environment:
      PROJECT_NAME: balancer_backend
      DJANGO_SETTINGS_MODULE: config.settings.local
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    entrypoint:
      ["/bin/bash", "-c", "python"]
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend