version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
<<<<<<< HEAD
      - ./config/env/env.prod.db
=======
      - ./config/env/.env.prod.db
>>>>>>> ac68347c12ced724206112843623ee8c515bd3ad
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    command: gunicorn balancer_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./config/env/env.prod
    depends_on:
      - db
<<<<<<< HEAD
=======
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    depends_on:
      - backend
>>>>>>> ac68347c12ced724206112843623ee8c515bd3ad

volumes:
  postgres_data: