version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=balancer
      - POSTGRES_PASSWORD=balancer
      - POSTGRES_DB=balancer_dev
  backend:
    build: 
      context: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./config/env/.env.dev
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    volumes:
      - staticfiles:/server/staticfiles
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  staticfiles: