version: '3.8'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    image: ghcr.io/codeforphilly/balancer-main/backend:latest
    command: ["/app/tools/wait-for-it.sh", "db:5432", "--", "python", "/app/backend/manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=balancer.settings
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    image: ghcr.io/codeforphilly/balancer-main/frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
