version: '3.8'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    image: balancer
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-backend
    environment:
      - DJANGO_SETTINGS_MODULE=balancer.settings
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
