version: "3"
services:
  balancer-backend:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/${NAMESPACE}:${DOCKER_TAG_VERSION}
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DJANGO_SETTINGS_MODULE: config.settings.local
    ports:
      - "8000:8000"
    volumes:
      - "../../../:/app"
