apiVersion: v1
data:
  {{- toYaml .Values.backend.env | nindent 2 }}
  SQL_PORT: "{{ .Values.postgresql.port }}"
  DJANGO_ALLOWED_HOSTS: |
    {{- $hosts := .Values.ingress.hosts -}}
    {{- $hostsList := "localhost frontend 127.0.0.1 [::1]" -}}
      {{- if .Values.ingress.enabled }}
        {{- range $index, $host := $hosts -}}
          {{- $hostsList = printf "%s %s" $hostsList $host.host -}}
        {{- end -}}
      {{- end }}
    {{ $hostsList }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend-env
