apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-frontend-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: frontend-static
                port:
                  number: 80