<<<<<<< HEAD
name: 'Release: Prepare PR'

on:
  push:
    branches: [ develop ]
=======
name: "Release: Prepare PR"

on:
  push:
    branches: [develop]
>>>>>>> 5d9968afe8f5ab373ab0379485cea79ba3253193

permissions:
  contents: read
  pull-requests: write

jobs:
  release-prepare:
<<<<<<< HEAD

    runs-on: ubuntu-latest
    steps:

    - uses: JarvusInnovations/infra-components@channels/github-actions/release-prepare/latest
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-branch: main
=======
    runs-on: ubuntu-latest
    steps:
      - uses: JarvusInnovations/infra-components@channels/github-actions/release-prepare/latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: main
>>>>>>> 5d9968afe8f5ab373ab0379485cea79ba3253193
